# Generated by Django 3.0.5 on 2022-11-17 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagstory',
            name='flagged',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flagstory',
            name='reportType',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
