# Generated by Django 4.1.7 on 2026-02-04 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pins", "0002_auto_20221117_0436"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pin",
            name="lastPersonEdit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lastPersonEditPins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pin",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userStories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
